### ISSUE TITLE
Not working on IOS: Cannot read property 'IsAndroid' of undefined

### ISSUE THREAD

**Issue by Frosty92** [zmxv/react-native-sound#36] opened 2016-05-17 23:12 UTC
The error is regarding the following line of code in `sound.js` : 

```
var RNSound = require('react-native').NativeModules.RNSound;
var IsAndroid = RNSound.IsAndroid;
```

I have followed the instructions exactly as outlined for IOS, so I have no idea why I am getting this error. 
This module works perfectly on Android.

**Comment by zmxv** [comment] 2016-05-17 23:13
Are you on the latest version? Are you seeing the issue with https://github.com/zmxv/react-native-sound-demo ?

**Comment by Frosty92** [comment] 2016-05-17 23:17
Yes, I am on the latest version. I will clone from the link you provided and get back to you asap.

**Comment by Frosty92** [comment] 2016-05-17 23:25
I am unable to run the demo project because I get the following error: Add RNCookieManagerIOS.h and RNCookieManagerIOS.m to your Xcode project despite running `npm install` and `rnpm link`

**Comment by zmxv** [comment] 2016-05-17 23:29
Weird. Neither the demo app nor the native module directly depends on RNCookieManager
https://github.com/zmxv/react-native-sound/search?utf8=%E2%9C%93&q=RNCookieManagerIOS
https://github.com/zmxv/react-native-sound-demo/search?utf8=%E2%9C%93&q=RNCookieManagerIOS

**Comment by Frosty92** [comment] 2016-05-17 23:42
The error is this line: `if (Platform.OS === 'ios') {
    invariant(RNCookieManagerIOS,`

**Comment by zmxv** [comment] 2016-05-17 23:47
This error seems to have nothing to do with the sound module.

**Comment by Frosty92** [comment] 2016-05-18 16:28
Back to the original issue, do you have any idea what's causing it?

**Comment by Frosty92** [comment] 2016-05-18 17:51
FYI, I am able to successfully run the demo project. Digging the sample audio.

**Comment by will-ockmore** [comment] 2016-05-19 10:39
Having the same issue, any updates @Frosty92?

**Comment by Frosty92** [comment] 2016-05-19 17:37
Unfortunately no.

**Comment by zmxv** [comment] 2016-05-19 20:25
I'm unable to reproduce the issue with the demo app.

**Comment by Roconda** [comment] 2016-06-02 11:06
I had this error as well when adding the dependencies but forgetting to recompile. After a new build it worked like a charm! cc @Frosty92

**Comment by will-ockmore** [comment] 2016-06-02 11:51
Mine was solved after reintalling node modules and recompiling - haven't had the issue since (touch wood)

**Comment by sydneyitguy** [comment] 2016-07-01 22:35
I have the same issue, and I tried reinstalling node module and recompiling, but it didn't help.
reinstalled by: `npm install react-native-sound --save`
recompiled by: `react-native run-ios`

is this what you did? @will-ockmore

**Comment by sydneyitguy** [comment] 2016-07-01 22:37
Stack trace is:
```
Unhandled JS Exception: undefined is not an object (evaluating 'RNSound.IsAndroid')

RCTFatal + 104
-[RCTExceptionsManager reportFatalException:stack:exceptionId:] + 588
__invoking___ + 140
-[NSInvocation invoke] + 286
-[NSInvocation invokeWithTarget:] + 54
-[RCTModuleMethod invokeWithBridge:module:arguments:] + 1887
-[RCTBatchedBridge _handleRequestNumber:moduleID:methodID:params:] + 680
__33-[RCTBatchedBridge handleBuffer:]_block_invoke.456 + 1274
_dispatch_call_block_and_release + 12
_dispatch_client_callout + 8
_dispatch_queue_drain + 1048
_dispatch_queue_invoke + 595
_dispatch_client_callout + 8
_dispatch_root_queue_drain + 890
_dispatch_worker_thread3 + 98
_pthread_wqthread + 1129
start_wqthread + 13
```

**Comment by sydneyitguy** [comment] 2016-07-02 09:43
I finally resolved issue by following steps (I don't know which one fixed the issue, so I'll put everything I did)

1. Kill processes on port 8081
2. `rm -rf ios/build/*` (Delete all files in iOS build folder)
3. Reboot
4. Open up in XCode and change the scheme from building for a `Release` to `Debug`.

Now I see `RNSound` object on ReactNative.

**Comment by ThaJay** [comment] 2016-08-12 12:41
I get
```
undefined is not an object (evaluating '_reactNativeSound.Sound.MAIN_BUNDLE')
```
probably related.
`react-native link` sets `react-native-sound` where the docs say `RNSound`. I changed that manually and the above error is what I end up with after copying a sound to the specified folder `android/app/src/main/res/raw`.

**Comment by RinorDreshaj** [comment] 2016-08-24 16:48
> Unhandled JS Exception: undefined is not an object (evaluating 'RNSound.IsAndroid')

Deleting all files in iOS build folder and restarting the packager solved the issue 

> rm -rf ios/build/*

**Comment by wilbyang** [comment] 2016-12-02 14:00
@RinorDreshaj there is no such folder as far as I can see. where do you find it?

**Comment by anhtata** [comment] 2016-12-07 21:12
I have got the same issue with Android undefined is not an object (evaluating 'RNSound.IsAndroid')

**Comment by anhtata** [comment] 2016-12-07 21:31
Luckily, I fixed by rebuild android and react-native run-android. Thanks all

**Comment by snsekar** [comment] 2016-12-11 03:07
@anhtata Please help me i am also facing issue in android. I tried 

>  react-native run-android

 but still same issue

**Comment by tsanthosh** [comment] 2016-12-13 01:23
@snsekar @Frosty92 @zmxv @will-ockmore @Roconda @sydneyitguy 

Had the same issue on iOS & Android and was able to fix it.

iOS: My fault I did not choose my target correctly i.e. under built target I had `myProjectTests` selected rather than `myProject`. Once I fixed this I did not receive any error on iOS.

Android: According to RN [docs](http://facebook.github.io/react-native/docs/native-modules-android.html#register-the-module) `RNSound` package should be added to `getPackages()` method of `MainApplication.java` rather than `MainActivity.java`. Once I changed this the error went away.

I am using RN version 0.39.2.

Hope this helps.

**Comment by tsanthosh** [comment] 2016-12-13 01:30
Looks like there is a [Pull Request](https://github.com/zmxv/react-native-sound/pull/85) already on this issue.

**Comment by bntzio** [comment] 2016-12-13 21:44
**I was able to fix the issue `undefined is not an object (evaluating 'RNSound.IsAndroid')` on iOS 💥.**

What I did was just to reinstall react-native-sound `npm install react-native-sound --save` and instead of linking it to xcode/android manually, I used `react-native link react-native-sound` to link it automatically, after that the error disappeared.

---

Just for reference, to play a sound just open xcode, and drag-drop your sound file into the root of the xcode project library:

```
--AppName
----Libraries
----AppNameTests
----Products
----Resources
----SoundFile.wav
```

Then tick *Copy items if needed*, *Create folder references* and in **add to targets** select your *AppName*, then click **finish** to add it to your project.

Now go to your Project **Build Phases** and make sure your sound file is listed on **Copy Bundle Resources**, if it's not in there, add it by drag-drop your sound file.

Now everything should be ready, just don't forget to run your app in xcode to build it.

Here's a sample code I'm using in my React Native app:

```
import React from 'react';
import { TouchableWithoutFeedback, Text } from 'react-native';
import Sound from 'react-native-sound';

class MyComponent extends Component {
  playSound() {
    const mySound = new Sound('tap.wav', Sound.MAIN_BUNDLE, (e) => {
      if (e) {
        console.log('error', e);
      } else {
        console.log('duration', mySound.getDuration());
        mySound.play();
      }
    });
  }

  render() {
    return (
      <TouchableWithoutFeedback onPress={this.playSound.bind(this)}>
         <Text>Play Sound!</Text>
      </TouchableWithoutFeedback>
    );
  }
}
```

And now it's 100% working, I tried it on iOS only, but the original error should be gone on both platforms.

Just don't forget to run the project with xcode, then you can use `react-native run-ios`, that's all!

Hope this is helpful! 😊

**Comment by benvium** [comment] 2017-02-09 09:09
Interesting - it's possible the differences between `react-native link react-native-sound` and the manual instructions may be due to #88

**Comment by Jarred-Sumner** [comment] 2017-02-25 00:45
I had this issue briefly, just after running `yarn add react-native-sound` and `react-native link` on iOS.

I fixed it by recompiling. I forgot to do that 🙈

**Comment by benvium** [comment] 2017-03-03 09:49
I'm closing this as folks have posted helpful solutions that seem to work for people

**Comment by DeanKamali** [comment] 2017-03-06 16:10
Running `react-native link` works, however it doesn't seems to do anything, I had this error as well, and I was able to resolve it by manually adding `RNSound.xcodeproj` to `Libraries` folder and drag and drop `libRNSound.a` to `Link Binary with Libraries` of my project.

**Comment by DeanKamali** [comment] 2017-03-06 16:11
@benvium  I'm not sure why would you close an issue and I'm seeing tone of people encountering this error?

**Comment by benvium** [comment] 2017-03-06 16:16
@DeanKamali Which version of the react-native cli and react native are you using? react-native link worked for me (no manual steps required) on 41.2, cli version 1.3.0, Xcode 8.2.1.

**Comment by DeanKamali** [comment] 2017-03-06 16:29
hmmm, I believe we both using same versions  
```
react-native-cli: 2.0.1
react-native: 0.41.2
xcode Version 8.2.1 (8C1002)
```

**Comment by benvium** [comment] 2017-03-06 16:33
@DeanKamali ok. I just tried:

```
react-native init TEST
cd TEST
npm i react-native-sound --save
react-native link
open ios/TEST.xcodeproj/
# open build phases
```
... and for me it linked the library correctly. What happens when you try?

**Comment by DeanKamali** [comment] 2017-03-06 16:41
@benvium I followed your steps verbatim and created new project and I can confirm that  `react-native link` correctly set things up. 
I'm not sure why I encountered that issue earlier, however following the manual process is not a big deal.  

Thanks for taking the time to check it out.

**Comment by benvium** [comment] 2017-03-06 16:46
@DeanKamali No problem. I'll re-close this ticket until the issue crops up again :-)

**Closed by benvium** 2017-03-06 16:46 UTC

**Comment by onpaws** [comment] 2017-03-08 06:43
Had the same experience as @DeanKamali 
I have more than one Xcode Target. I [manually selected](https://facebook.github.io/react-native/docs/linking-libraries-ios.html#step-2) my dev target and linked libRNSound.a by dragging (see docs), re-built from Xcode and it worked.

**Comment by selcukitmis** [comment] 2017-04-28 13:40
I solved this problem.
Solution; close android / ios emulator and close android Studio / XCode and close terminal / cmd. Restart all and it worked.

**Comment by nickhillwd** [comment] 2017-05-29 11:45
I have been unable to resolve the problem following any of the above steps. I am using create-react-native-app. Has anyone had found a solution to using create-react-native-app?

**Comment by ofirgeller** [comment] 2017-05-29 12:01
I believe your problem is unrelated.  create-react-native-app creates an expo app, and that means it does not work the same when it comes to native modules. you might have to do something called "eject" but this is not just a tiny step, you really should learn more about what it means to have an expo app.

**Comment by jpapillon** [comment] 2017-06-28 20:43
You need to delete your derived data in XCode: `/Users/{yourUserName}/Library/Developer/Xcode/DerivedData`

**Comment by novalagung** [comment] 2017-07-08 10:44
I'm able to solve this error, by re-linking the libraries again. It's pretty weird haha

```bash
react-native link
react-native run-ios
```

**Comment by lukkyjoe** [comment] 2017-07-12 18:25
I am hating myself because I frantically scrolled through the github comments looking for a solution but only after 25 minutes did I realize that I forgot to run `react-native link react-native-sound` as laid out in the initial instructions. That solved my problem.

**Comment by Andruschenko** [comment] 2017-08-17 05:48
I only get the error when running unit tests!
Building an playing sounds works perfectly fine.
What could be the reason for it?

**Comment by tirrorex** [comment] 2017-11-28 15:50
Linking doesn't work whether i relink the library or not, manual installation doesn't work either.
None of the above workaround worked aswell.

Build on ios, both debug and release tested.
App is native with a react-native view (so not created with create react-native app)

ps : fixed this by doing a pod install after linking the library. Now i got to get it to work.

**Comment by tuthanh82** [comment] 2018-03-05 10:07
In my case, I used: 

npm i --save react-native-sound 

and then

react-native link react-native-sound

But then I found under /node_modules/react-native-sound/, there is no 'android' folder.

So I downloaded 'react-native-sound' manually, copy the 'android' folder to /node_modules/react-native-sound/ and rebuilt. It seems no more error.

**Comment by CodeMuz** [comment] 2018-09-21 16:59
The Error was appearing when running Jest, and being flagged as soon as the 'react-native-sound' was being imported. I'm having success by importing a mock file into the test, containing:
```
jest.mock('NativeModules', () => {
  return {
    RNSound: {
      IsAndroid: true
    }   
  };
});
```

**Comment by vladbars** [comment] 2019-06-25 11:00
Make sure that you run `pod install` after `react-native link react-native-sound` in case you are use pods. In other case link it manually [https://github.com/zmxv/react-native-sound/issues/36#issuecomment-284443489](url)

**Comment by atrombet** [comment] 2020-02-01 18:20
@vladbars comment worked for me. I had to cd into the `ios` directory ad run `pod install`.

**Comment by mcavalcante28** [comment] 2020-03-16 19:36
PLEASE, PUT IN  THE DOCUMENTATION WITH CAPITAL LATTERS: 

"REBUILD THE APP AFTER IMPORT THE LIBRARY"

Thanks a lot.
