### ISSUE TITLE
[Android] java.lang.RuntimeException - Possible Race Condition

### ISSUE THREAD

**Issue by K-Leon** [zmxv/react-native-sound#106] opened 2017-02-09 15:36 UTC
I've just observed this Crash in the wild - i could imagine that it could be some sort of Race Condition or maybe both - onError and onCompletion -  is called at a certain condition.

```
Fatal Exception: java.lang.RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
       at com.facebook.react.bridge.CallbackImpl.invoke(CallbackImpl.java:32)
       at com.zmxv.RNSound.RNSoundModule$1.onCompletion(RNSoundModule.java:81)
       at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:2538)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by benvium** [comment] 2017-02-09 15:51
@K-Leon Interesting - if onError and onCompletion were both called this'd definitely happen. Not sure *why* that'd happen, but we could protect against it in the Java code

**Comment by benvium** [comment] 2017-02-09 15:56
I made a PR that may fix this. I don't have a good test case though at the moment.

**Comment by K-Leon** [comment] 2017-02-09 16:05
Wow.. this was fast! Thank you very much! I'll push this asap to production and let you know if i see this error again

**Comment by rohitgoyal** [comment] 2017-02-27 10:22
Is this resolved?

**Comment by K-Leon** [comment] 2017-02-27 10:36
I just checked Error logs and i've seen this one again - i have no idea how this can happen.

**Comment by henninghall** [comment] 2017-03-01 18:09
I can confirm that this bug still exists even when using the fixes #107 and #87. Ideas: Could it possibly has something to to with not releasing resources after using them? Interferences with other media playing apps? Restarting sounds? Playing sounds with volume 0?

**Comment by ndbroadbent** [comment] 2017-04-19 23:46
I think this could be similar to the race condition I fixed in #153.

It might need a fix similar to this: https://github.com/ivpusic/react-native-image-crop-picker/issues/235

**Comment by ndbroadbent** [comment] 2017-04-19 23:52
I've submitted a PR with this fix: #154

@henninghall and @K-Leon, please let me know if this fixes it for you.

**Comment by henrikra** [comment] 2017-04-25 16:17
This is serious bug and needs to be fixed :(

**Comment by benvium** [comment] 2017-04-25 16:18
@henrikra Does #154 fix this issue for you? If so I'll merge it now

**Comment by henrikra** [comment] 2017-04-25 16:20
@benvium How to reproduce this crash? I haven't been able to reproduce this by myself. We have caught this bug with our crash reporter so our users have been experiencing this

**Comment by benvium** [comment] 2017-04-25 16:23
@henrikra Fair point - I've merged #153 and #154. They both are sensible changes. Let us know if you experience fewer crash reports as a result. Thanks for your help.

**Closed** 2017-04-25 16:22 UTC
Labels: bug

**Comment by henrikra** [comment] 2017-04-25 16:25
@benvium We will update this week and lets see the results :) Probably if you don't get message from me it is working ;)

**Comment by henrikra** [comment] 2017-04-25 16:25
@benvium Are you going to do new release btw? 0.9.2?

**Comment by benvium** [comment] 2017-04-25 16:29
There are quite a few changes since 0.9.1 so am thinking we should bump to 0.10.0 to prevent issues with npm auto-upgrading everyone

**Comment by henrikra** [comment] 2017-04-25 16:30
Good idea!

**Comment by benvium** [comment] 2017-04-25 17:00
Released as v0.10.0 https://github.com/zmxv/react-native-sound/releases/tag/v0.10.0

**Comment by henrikra** [comment] 2017-05-24 04:59
Still experiencing this on react-native-sound `0.10.1`
Crash was from this device:
![image](https://cloud.githubusercontent.com/assets/12229968/26387495/c873e07c-4056-11e7-9840-7699342e85ed.png)

```
java.lang.RuntimeException Illegal callback invocation from native module. This callback type only permits a single invocation from native code. 
    CallbackImpl.java:32 com.facebook.react.bridge.CallbackImpl.invoke
    RNSoundModule.java:108 com.zmxv.RNSound.RNSoundModule$2.onError
    MediaPlayer.java:2279 android.media.MediaPlayer$EventHandler.handleMessage
    Handler.java:102 android.os.Handler.dispatchMessage
    Looper.java:149 android.os.Looper.loop
    MessageQueueThreadImpl.java:208 com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run
    Thread.java:841 java.lang.Thread.run
```

**Comment by ndbroadbent** [comment] 2017-05-24 05:02
Damn, I could have sworn that [this commit](https://github.com/zmxv/react-native-sound/commit/f31895b095603acf1331fcd52be2c6ed483601e8) would fix it. I'll take another look.

**Comment by henrikra** [comment] 2017-05-24 05:03
Have you tried it with "Don't keep activities on" setting?

**Comment by ndbroadbent** [comment] 2017-05-24 05:05
Sorry I'm not sure what that is. But also I just realized that my commit doesn't handle the case where both onComplete and onError are called. I think that's causing the crash

**Comment by henrikra** [comment] 2017-05-24 05:07
Good point. Also check this https://stackoverflow.com/questions/22400859/dont-keep-activities-what-is-it-for
It is very common on Android to develop with this setting on since the operating system can kill the app's activity anytime it want.

**Comment by ndbroadbent** [comment] 2017-05-24 05:11
Oh thanks! Yeah I should definitely test with that setting.

I'll try to push one more fix for this. I think I just need to set both callbacks to null after one is called.

**Comment by henninghall** [comment] 2017-05-24 06:46
I made an temporary fix by putting a try catch around the `callback.invoke(true);` which at least prevents the app from crashing. I works and I have never encountered any issues with it but I am also not using the callback from the play method.

**Comment by ndbroadbent** [comment] 2017-05-24 06:52
The try/catch is an even better idea. I'll send a PR with that

**Comment by henrikra** [comment] 2017-05-24 06:53
Great!

**Comment by henrikra** [comment] 2017-05-29 04:57
@ndbroadbent Any news on this? We got the crash again :/

```
java.lang.RuntimeException Illegal callback invocation from native module. This callback type only permits a single invocation from native code. 
    CallbackImpl.java:32 com.facebook.react.bridge.CallbackImpl.invoke
    RNSoundModule.java:108 com.zmxv.RNSound.RNSoundModule$2.onError
    MediaPlayer.java:2279 android.media.MediaPlayer$EventHandler.handleMessage
    Handler.java:102 android.os.Handler.dispatchMessage
    Looper.java:149 android.os.Looper.loop
    MessageQueueThreadImpl.java:208 com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run
    Thread.java:841 java.lang.Thread.run
```

**Comment by ndbroadbent** [comment] 2017-05-29 05:00
Oops, sorry I forgot about this! Will push that today

**Comment by blaues0cke** [comment] 2017-05-31 07:55
Faced the same issue and figured out that this only happens (so far is I could check this for now) when two ore more sounds are played at the same time. So I used the callback of `play` to workaround this in my js code - maybe this will help you:

`../helper/Sound.js`:
```
import Sound from 'react-native-sound';

Sound.setCategory('Ambient');

let soundPlaying = false;

const soundLoadedCallback = (error) => {
    // ...
};

const soundPlayedCallback = (success) => {
    soundPlaying = false;
};

const beep_off = new Sound('beep_off.wav', Sound.MAIN_BUNDLE, soundLoadedCallback);
const beep_on  = new Sound('beep_on.wav',  Sound.MAIN_BUNDLE, soundLoadedCallback);


export default class SoundManager {
    static allowedToPlay() {
        if (soundPlaying) {
            console.log('Prevented sound from playing');

            return false;
        }

        soundPlaying = true;

        return true;
    }

    static flashLightOff() {
        if (SoundManager.allowedToPlay()) {
            beep_off.play(soundPlayedCallback);
        }
    }

    static flashLightOn() {
        if (SoundManager.allowedToPlay()) {
            beep_on.play(soundPlayedCallback);
        }
    }

    // ...
}
```

So in my case I can call `Sound.flashLightOn()` (`import Sound from '../helper/Sound';`) as often as I want but it is only one sound played at the same time - this seems to workaround this issue.

**Comment by henrikra** [comment] 2017-06-04 09:50
@ndbroadbent What is the status of that PR coming? :D Still getting lots of these crashes

**Comment by henrikra** [comment] 2017-06-14 07:11
@henninghall or @ndbroadbent Can you guys make PR to fix this issue? We have had 59 crashes from this last 30 days. What is the status of this?

**Comment by henninghall** [comment] 2017-06-14 09:50
@henrikra #202 there you go

**Comment by henninghall** [comment] 2017-06-14 09:50
@henrikra there you go, submitted PR #202
