### ISSUE TITLE
Music stops on initial app startup 

### ISSUE THREAD

**Issue by austincline09** [zmxv/react-native-sound#559] opened 2019-03-25 16:26 UTC
If I'm playing music from any player and then boot up my app with react-native-sound, the music stops no matter what. However, once the app is open and in the background everything is fine. So it's just on the initial start up of the app. I've noticed on the simulator, it asks my computer for microphone access on startup as well. I'm looking to get rid of that because I think it's related

**Comment by olegwn** [comment] 2019-04-03 15:56
same problem on iOS here

adding this to AppDelegate.m per instructions on the internet did not help :(
```
  [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryAmbient error:nil];
  [[AVAudioSession sharedInstance] setActive:YES error:nil];
```

**Comment by bkmed** [comment] 2019-06-12 14:45
same here any solution yet ?

**Comment by ammichael** [comment] 2019-08-13 11:45
Any solution to this? I've ran into it as well.

**Comment by jweinraub** [comment] 2019-08-30 14:48
I am keen to know this too!

**Comment by paulmelnikow** [comment] 2019-08-30 16:13
If you're having the same issue, please :+1: the top post instead of adding a comment. It makes less noise for everyone 😃

**Comment by danleveille** [comment] 2019-10-20 06:45
This is a duplicate of #431, right?

**Comment by Farhankhaliid** [comment] 2021-05-25 20:25
@austincline09  can you please let me know how you git ride of this issue . i am also facing same issue while app boot up music stops.

**Comment by Farhankhaliid** [comment] 2021-05-25 20:33
@olegwn  any solution?

**Comment by paulmelnikow** [comment] 2021-05-26 01:23
Closing in favor of #431.

**Closed by paulmelnikow** 2021-05-26 01:23 UTC
Labels: question
