### ISSUE TITLE
undefined RNSound.setLooping

### ISSUE THREAD

**Issue by huangzuizui** [zmxv/react-native-sound#7] opened 2015-12-25 06:23 UTC
undefined is not an object (evaluating 'RNSound.setLooping')?

**Comment by zmxv** [comment] 2015-12-25 06:39
I assume you're on iOS. What version of React Native and XCode are you using?

**Comment by huangzuizui** [comment] 2015-12-25 06:51
react native is "^0.14.2" and xcode is "7.0.1", thank u

2015-12-25 14:39 GMT+08:00 Zhen Wang <notifications@github.com>:

**Comment by zmxv** [comment] 2015-12-25 06:57
I was testing it with RN 0.17.0. I'll downgrade to 0.14.2 and try to reproduce the bug.

**Comment by huangzuizui** [comment] 2015-12-25 07:03
i will try it with 0.17.0. by the way, u r from china?

2015-12-25 14:57 GMT+08:00 Zhen Wang <notifications@github.com>:

**Comment by zmxv** [comment] 2015-12-25 07:15
I can't reproduce the bug after downgrading to RN 0.14.2, but commit 82209a0 might have fixed your issue. Can you upgrade to react-native-sound v0.7.2 and give it a try?

BTW, yes.

**Comment by zmxv** [comment] 2015-12-27 20:49
@huangzuizui Can you please confirm?

**Comment by huangzuizui** [comment] 2015-12-28 12:27
i try it on ios today with  RN 0.17.0 ,it works fine. and on android is ok. thank u..

**Comment by zmxv** [comment] 2015-12-28 18:06
Thanks for the confirmation. I'm closing the issue.

**Closed by zmxv** 2015-12-28 18:06 UTC

**Comment by hasen6** [comment] 2016-01-20 07:45
Getting this issue on 0.18
