### ISSUE TITLE
IOS error Object {code: "ENSOSSTATUSERRORDOMAIN2003334207"

### ISSUE THREAD

**Issue by keung725** [zmxv/react-native-sound#64] opened 2016-08-28 12:24 UTC
error Object {code: "ENSOSSTATUSERRORDOMAIN2003334207", message: "The operation couldn’t be completed. (OSStatus error 2003334207.)", nativeStackIOS: Array[17], domain: "NSOSStatusErrorDomain"}

It is not work if I using mp3 file in my component folder
Music/
 music.js
 background1.mp3

playSound() {
    var s = new Sound('background2.mp3', Sound.DOCUMENT, (e) => {
      if (e) {
        console.log('error', e);
      } else {
        console.log('duration', s.getDuration());
        s.play();
      }
    });
  }

**Comment by tsella** [comment] 2016-09-09 00:34
add the file to Xcode Resources.

**Comment by mathiasericsson** [comment] 2016-09-23 10:55
Hi! I have the same problem, I've followed the readme file and added the mp3 as a resource in Xcode project. Also I've added the library according to readme-file. Below is my code, the path on the file in X-code project is set to "Relative to Project" and is "../audio/soundfile.mp3"

```
var music = new Sound('../audio/soundfile.mp3', Sound.MAIN_BUNDLE, (error) => {

         if (error) {
             alert('error:' + error);
            console.log('failed to load the sound', error);
         }
         else { // loaded successfully
             console.log('duration in seconds: ' + music.getDuration() +
            'number of channels: ' + music.getNumberOfChannels());
         }

     });
```

The error I get is,
`<Notice>: 'failed to load the sound', { code: 'ENSOSSTATUSERRORDOMAIN2003334207',
	  message: 'The operation couldn’t be completed. (OSStatus error 2003334207.)',
	  nativeStackIOS:
	   [ '0   ElevatorMusic                       0x000000010be76896 RCTJSErrorFromCodeMessageAndNSError + 134',
	     '1   ElevatorMusic                       0x000000010be767c3 RCTJSErrorFromNSError + 275',
	     '2   ElevatorMusic                       0x000000010bdd151e -[RNSound prepare:withKey:withCallback:] + 958',
	     '3   CoreFoundation                      0x000000010dad705c __invoking___ + 140',
	     '4   CoreFoundation                      0x000000010dad6ee1 -[NSInvocation invoke] + 289',
	     '5   CoreFoundation                      0x000000010daeeed6 -[NSInvocation invokeWithTarget:] + 54',
	     '6   ElevatorMusic                       0x000000010bdfb1af -[RCTModuleMethod invokeWithBridge:module:arguments:] + 1887',
	     '7   ElevatorMusic                       0x000000010be53d88 -[RCTBatchedBridge _handleRequestNumber:moduleID:methodID:params:] + 680',
	     '8   ElevatorMusic                       0x000000010be52eca __33-[RCTBatchedBridge handleBuffer:]_block_invoke.494 + 1274',
	     '9   libdispatch.dylib                   0x0000000111a2c810 _dispatch_call_block_and_release + 12',
	     '10  libdispatch.dylib                   0x0000000111a4e12e _dispatch_client_callout + 8',
	     '11  libdispatch.dylib                   0x0000000111a33523 _dispatch_queue_serial_drain + 1018',
	     '12  libdispatch.dylib                   0x0000000111a33cf3 _dispatch_queue_invoke + 1118',
	     '13  libdispatch.dylib                   0x0000000111a3409b _dispatch_queue_override_invoke + 376',
	     '14  libdispatch.dylib                   0x0000000111a35a0e _dispatch_root_queue_drain + 506',
	     '15  libdispatch.dylib                   0x0000000111a357b4 _dispatch_worker_thread3 + 113',
	     '16  libsystem_pthread.dylib             0x0000000111df44de _pthread_wqthread + 1129',
	     '17  libsystem_pthread.dylib             0x0000000111df2341 start_wqthread + 13' ],
	  domain: 'NSOSStatusErrorDomain' }`

**Comment by mathiasericsson** [comment] 2016-09-23 11:05
Hmm... for some reason it just started working. Not sure what I did though, but I stopped getting the error and suddenly I heard the sound.

**Comment by ArondeParon** [comment] 2016-11-04 14:00
Have you ever figured out what you did to fix this? I experience the same issue.

**Comment by benvium** [comment] 2017-02-10 13:56
It sounds like the issue has been resolved, so I'm closing this.

**Closed by benvium** 2017-02-10 13:57 UTC

**Comment by lukecwilliams** [comment] 2017-06-30 21:56
If anyone else arrives here: we got this working after putting the file in the Xcode Resources directory, then redeploying with `react-native run-ios`.  Not sure if restarting the packager was necessary.

**Comment by bopeterson** [comment] 2017-07-20 06:14
Got the same error as above, but closing xcode and opening it again made it work. Thank you lukecwilliams for leading me in the right direction

**Comment by lossen** [comment] 2017-09-04 12:03
same error
I add file in the Xcode Resources and redeploy with react-native run-ios
but to no avail :(

**Comment by gvenk** [comment] 2017-09-04 21:14
@lossen sometimes you have to close XCode and open it again before it starts working after adding the file to the XCode resources. 

A clean build will also help ;-)

**Comment by trepidity** [comment] 2017-09-05 15:16
Does this relate to relinking?

**Comment by OmarelBouari1** [comment] 2017-10-19 09:09
hello
I have the same problem with IOS when i try this 
playTrack(parent){
      const track = new Sound('https://www.soundjay.com/button/button-1.mp3',null, (e) => {
        if (e) {
          console.log(e)     
        } else {
          track.play()
        }
      })
  }
work good but when i try with the link firebase storage not working
playTrack(parent){
      const track = new Sound('https://firebasestorage.googleapis.com/v0/b/prj1-aa7b3.appspot.com/o/Chat_audio%2Fbutton-1%20(1).mp3?alt=media&token=39d18256-25c0-4948-b0d8-12c3f626a26a',null, (e) => {
        if (e) {
          console.log(e)     
        } else {
          track.play()
        }
      })
  }
The error I receive is:

[info][tid:com.facebook.react.JavaScript] { code: 'ENSOSSTATUSERRORDOMAIN-10875',
  nativeStackIOS: 
   [ '0   MyApp                              0x00000001001ac318 RCTJSErrorFromCodeMessageAndNSError + 152',

**Comment by amed** [comment] 2017-11-07 23:37
it seems that that this issue is back again:
```
    "react": "16.0.0",
    "react-native": "0.50.0",
```
```
componentDidMount () {
    const url = 'http://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3'
    this.player = new Sound(url, Sound.MAIN_BUNDLE, (error) => {
      if (error) {
        console.log('failed to load the sound', error)
        return
      }
      console.log('duration in seconds: ' + this.player.getDuration() + 'number of channels: ' + this.player.getNumberOfChannels())
    })
  }
```
Native stack `nativeStackIO`:

```
0: "0   the_app                0x000000010b7f7276 RCTJSErrorFromCodeMessageAndNSError + 134"
1: "1   the_app                0x000000010b7f71a3 RCTJSErrorFromNSError + 275"
2: "2   the_app                0x000000010b98eef5 -[RNSound prepare:withKey:withOptions:withCallback:] + 1493"
3: "3   CoreFoundation                      0x000000010e0f549c __invoking___ + 140"
4: "4   CoreFoundation                      0x000000010e0f5370 -[NSInvocation invoke] + 320"
5: "5   CoreFoundation                      0x000000010e10dd56 -[NSInvocation invokeWithTarget:] + 54"
6: "6   the_app                0x000000010b7a59bc -[RCTModuleMethod invokeWithBridge:module:arguments:] + 2796"
7: "7   the_app                0x000000010b83c332 _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicE + 786"
8: "8   the_app                0x000000010b83be5f _ZZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEiENK3$_0clEv + 127"
9: "9   the_app                0x000000010b83bdd9 ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 25"
10: "10  libdispatch.dylib                   0x00000001127eb273 _dispatch_call_block_and_release + 12"
11: "11  libdispatch.dylib                   0x00000001127ec2b5 _dispatch_client_callout + 8"
12: "12  libdispatch.dylib                   0x00000001127f3e3f _dispatch_queue_serial_drain + 654"
13: "13  libdispatch.dylib                   0x00000001127f4690 _dispatch_queue_invoke + 329"
14: "14  libdispatch.dylib                   0x00000001127f0d94 _dispatch_queue_override_invoke + 477"
15: "15  libdispatch.dylib                   0x00000001127f6a72 _dispatch_root_queue_drain + 568"
16: "16  libdispatch.dylib                   0x00000001127f67dc _dispatch_worker_thread3 + 119"
17: "17  libsystem_pthread.dylib             0x0000000112ca15a2 _pthread_wqthread + 1299"
18: "18  libsystem_pthread.dylib             0x0000000112ca107d start_wqthread + 13"
```

**Comment by FRodrigues21** [comment] 2017-11-25 18:10
@amed  Had this problem.
Solved it by adding Sound.MAIN_BUNDLE to the Sound constructor and moving the .mp3 files to the resources folder of the project in XCode.

_(Note: Keeps working on Android without problems)_

**Constructor**
`var Beep = new Sound('beep_high.mp3', Sound.MAIN_BUNDLE);`

**Folder structure**
<img src="https://i.gyazo.com/c11849f401e4a1e85f18742f63554bf5.png" width="200" />

**Comment by amed** [comment] 2017-11-27 08:01
Thanks @FRodrigues21 for response, in my example the file is uri. BUT tried also to download it with [react-native-fetch-blob](https://github.com/wkh237/react-native-fetch-blob) and then play it, it cause same issue.

**Comment by poc7667** [comment] 2017-12-09 20:30
Any workaround to play sound over HTTP protocol? didn't see any successful example

**Comment by trepidity** [comment] 2018-01-10 03:45
take a look at #334

**Comment by andyesp** [comment] 2018-01-12 19:17
@FRodrigues21 solution worked for me in iOS and Android

**Comment by SamiChab** [comment] 2018-01-24 21:00
Why should I 
> add the file to Xcode Resources

? I'm trying to read a file I just recorded, that just got stored in the phone's internal storage...

**Comment by fatfatson** [comment] 2018-02-01 16:45
have the same problem in IOS simulator, 
but found a workaround:
change RNSound.m line194-197 to
```
fileNameUrl = [NSURL URLWithString: fileName];
NSData* data = [NSData dataWithContentsOfURL:fileNameUrl] ;
player = [[AVAudioPlayer alloc]
              initWithData:data
              error:&error];
```

it seems that AVAudioPlayer.initWithContentsOfURL could not load directly with filename , we have to first read it into memory then it's happy to load.

**Comment by bdrobinson** [comment] 2018-03-11 11:36
I'm also unable to get this working either on simulator or on an actual device – I've downloaded an mp3 file and saved it to my app's documents directory but get the same error when I try and create a `Sound`.  I haven't been able to try the solution posted by @fatfatson but that would require some library changes anyway. Has anyone managed to solve this?

**Comment by hoscarcito** [comment] 2018-04-07 07:06
@fatfatson  I tried your fix but it's not working either. I'm recording some audios and then try to reproduce them but sometimes (1 out of 3) the file is not loaded.
Thanks!

**Comment by amed** [comment] 2018-04-09 08:34
Can you please @benvium reopen this issue!?
it seems like it is still not solved.

**Comment by TylerNoblett** [comment] 2018-04-09 16:11
@bdrobinson - were you able to find a fix? I'm also downloading the files to the filesystem and am getting this same error, even after trying every solution listed in the repo (#334, #89, #321, #324, #89)

**Comment by tmjordan** [comment] 2019-05-28 18:58
Just replace Sound.MAIN_BUNDLE by an empty string.
Worked for me

**Comment by chellongCoder** [comment] 2019-07-23 03:58
> Just replace Sound.MAIN_BUNDLE by an empty string.
> Worked for me

thanks, working for me

**Comment by adancarrasco** [comment] 2019-11-17 10:26
For iOS what worked for me is the following:
1. Checked that my resource file was being played in xCode
  - Open xCode
  - Select the file
  - Click play in the xCode player
2. Once it was playing sound (had issues with some files, possibly encoding), 
  - Add the file as resource (Make sure is in Build Phases)
3. Compile the project in xCode and run it from there
  - Note: Every time you change the resources or expect new resources you need to compile your Native application either by doing it from xCode or `npm run ios`

This is my code:
```JS
const sound = new Sound(
    "myFile.mp3",
    Sound.MAIN_BUNDLE,
    error => {
      if (error) {
        console.log("failed to load the sound", error);
        return;
      }
      sound.play(() => sound.release());
    }
  );
// The play dispatcher
sound.play();
```

**Comment by allindeveloper** [comment] 2020-04-17 05:09
> Just replace Sound.MAIN_BUNDLE by an empty string.
> Worked for me

Worked for me too!!!

**Comment by aprilmintacpineda** [comment] 2021-01-02 05:32
Handling both android and ios:

```js
import { Platform } from 'react-native';
import Sound from 'react-native-sound';

const mainBundle = Platform.OS === 'ios'
  ? encodeURIComponent(Sound.MAIN_BUNDLE)
  : Sound.MAIN_BUNDLE;

export const notifAlert = new Sound('notif_alert.mp3', mainBundle, error => {
  if (error) console.error(error);
});
```

**Comment by nobnisai** [comment] 2021-01-29 07:41
> hello
> I have the same problem with IOS when i try this
> playTrack(parent){
> const track = new Sound('https://www.soundjay.com/button/button-1.mp3',null, (e) => {
> if (e) {
> console.log(e)
> } else {
> track.play()
> }
> })
> }
> work good but when i try with the link firebase storage not working
> playTrack(parent){
> const track = new Sound('https://firebasestorage.googleapis.com/v0/b/prj1-aa7b3.appspot.com/o/Chat_audio%2Fbutton-1%20(1).mp3?alt=media&token=39d18256-25c0-4948-b0d8-12c3f626a26a',null, (e) => {
> if (e) {
> console.log(e)
> } else {
> track.play()
> }
> })
> }
> The error I receive is:
> 
> [info][tid:com.facebook.react.JavaScript] { code: 'ENSOSSTATUSERRORDOMAIN-10875',
> nativeStackIOS:
> [ '0 MyApp 0x00000001001ac318 RCTJSErrorFromCodeMessageAndNSError + 152',

replace the 'MAIN_BUNDLE' with null works fine for me. Not sure about firebase though

**Comment by Sargnec** [comment] 2021-04-27 23:05
> ```js
> const mainBundle = Platform.OS === 'ios'
>   ? encodeURIComponent(Sound.MAIN_BUNDLE)
>   : Sound.MAIN_BUNDLE;
> ```

Thank you. Worked for me

**Comment by usamaabutt** [comment] 2021-07-24 09:04
> Handling both android and ios:
> 
> ```js
> import { Platform } from 'react-native';
> import Sound from 'react-native-sound';
> 
> const mainBundle = Platform.OS === 'ios'
>   ? encodeURIComponent(Sound.MAIN_BUNDLE)
>   : Sound.MAIN_BUNDLE;
> 
> export const notifAlert = new Sound('notif_alert.mp3', mainBundle, error => {
>   if (error) console.error(error);
> });
> ```

It works for me. Thank you @aprilmintacpineda

**Comment by minhchienwikipedia** [comment] 2021-12-26 10:06
> > hello I have the same problem with IOS when i try this playTrack(parent){ const track = new Sound('https://www.soundjay.com/button/button-1.mp3',null, (e) => { if (e) { console.log(e) } else { track.play() } }) } work good but when i try with the link firebase storage not working playTrack(parent){ const track = new Sound('https://firebasestorage.googleapis.com/v0/b/prj1-aa7b3.appspot.com/o/Chat_audio%2Fbutton-1%20(1).mp3?alt=media&token=39d18256-25c0-4948-b0d8-12c3f626a26a',null, (e) => { if (e) { console.log(e) } else { track.play() } }) } The error I receive is:
> > [info][tid:com.facebook.react.JavaScript] { code: 'ENSOSSTATUSERRORDOMAIN-10875', nativeStackIOS: [ '0 MyApp 0x00000001001ac318 RCTJSErrorFromCodeMessageAndNSError + 152',
> 
> Did you make it work ? I have the same issue.

Same to me, any update?

**Comment by pierroo** [comment] 2022-02-04 16:40
Facing the same issue too; anyone found a solution? :/
@AnthonyLabaere @minhchienwikipedia ?

Right now I am starting to believe it is linked with NSAllowsArbitraryLoads / NSAppTransportSecurity config in info.plist, since this issue only happens on iOS with remote url.

If you guys wanna participate to the investigation...

**Comment by tmjordan** [comment] 2022-02-04 17:43
@pierroo i have the same problem. For me it started after i upgraded react native to 0.66

**Comment by pierroo** [comment] 2022-02-04 17:49
Now that's unfortunate; I am also using latest react native version (0.66)
Using react-native-sound 0.11.1

I am using audio files stored in firebase storage, in an .mp4 format.
Those audio files are beforehand recorded with 'react-native-sound-recorder'
I can open those files in my browser, and they play as expected
I am also using an empty string bundle path
It works perfectly on android, but not on iOS
I tried with different remote sound (if that matters, I tried with 'https://www2.cs.uic.edu/~i101/SoundFiles/ImperialMarch60.wav') and it works there.

Do you have any similarities here?

**Comment by tmjordan** [comment] 2022-02-04 18:07
My audio files are stored in Amazon S3
I use 'react-native-audio' to record files
I use the empty string, and it used to work before the upgrade (iOS and Android)
Now it works only on Android

**Comment by tmjordan** [comment] 2022-02-04 18:09
I have set 'NSAllowsArbitraryLoads / NSAppTransportSecurity'  to false and even removed  it on my Info.plist. But the problem persists

**Comment by pierroo** [comment] 2022-02-04 18:27
Have you tried with the sampe link I sent above if the audio played on your end?
If it does: then we are on the same boat.
If it does not work, then that means your problem is elsewhere in your code, in which case copy / pasting it here would be helpful for investigating

**Comment by pierroo** [comment] 2022-02-06 10:30
Okay some additional information following some investigation:
Any remote link that ends with a proper audi extension ( *.mp3, *.wav, *.aac etc) will be read without issue by react native sound.

However, as soon as we start playing with firebase / amazon url, that ends with a token and no file extension in their url, then the error happens.
So clearly ios or react native sound doesn't like an audio file without a proper url / extension...

And I still can't find my way around it.
Might need to first download the file with rn fetch blob, have a local url, and play it with sound then?
Ugly workaround since it works fine on android, but for ios this might now be required?

**Comment by minhchienwikipedia** [comment] 2022-02-08 09:14
@pierroo I had created a sound manager package, you can try it, I also have an option for download and play as a local file. I'm using it and don't get any issues, hope it's helpful!  https://github.com/minhchienwikipedia/react-native-sound-manager

**Comment by tmjordan** [comment] 2022-06-25 09:09
Hi @minhchienwikipedia,
Is it possible to increase audio speed with your package?

**Comment by ximomompo** [comment] 2022-07-28 07:52
Hi @pierroo, I had same issue with files from firebase storage. I solved it by a different approach:

```javascript
const storageRef = '/audios/audios_test.mp3';
const filename = storageRef.split('/').pop();
const filePath = `${utils.FilePath.DOCUMENT_DIRECTORY}/${filename}`;
await storage().ref(storageRef).writeToFile(filePath);
const sound = new Sound(filePath, '', e => { if(e) console.error(e) })
```

Works on Android and iOS

**Comment by lmarques6** [comment] 2022-09-30 15:32
If you recently upgraded react-native-sound to 0.11.1+, the package added filepath encoding on the native side, so if you already have the sound files correctly in the Xcode resources folder, check if you had `encodeUri` when defining your filepath and remove it. See info [here](https://github.com/zmxv/react-native-sound/issues/772#issuecomment-1263708313)

**Comment by jhanvelez** [comment] 2024-01-26 21:02
> @amed Had this problem. Solved it by adding Sound.MAIN_BUNDLE to the Sound constructor and moving the .mp3 files to the resources folder of the project in XCode.
> 
> _(Note: Keeps working on Android without problems)_
> 
> **Constructor** `var Beep = new Sound('beep_high.mp3', Sound.MAIN_BUNDLE);`
> 
> **Folder structure** <img alt="" width="200" src="https://camo.githubusercontent.com/ae8dbfd1b997f6db04d7e94b1bdc765b38b0972828c95e7cd2918f2fcfd1a825/68747470733a2f2f692e6779617a6f2e636f6d2f63313138343966343031653461316538356631383734326636333535346266352e706e67">

If the folder does not exist, just create it, clean the project and then run again.

**Comment by TajGoud** [comment] 2024-05-03 07:34
"domain":"NSOSStatusErrorDomain",
"message":"The operation couldn’t be completed. (OSStatus error 2003334207.)",





AnyOne has any idea i have tried with openAI but getting the same errror for everything.

This is the code:
` fetch('https://api.openai.com/v1/audio/speech', {
      method: 'POST',
      body,
      headers: options.headers,
    })
      .then(async response => {
        const mainBundle =
          Platform.OS === 'ios'
            ? encodeURIComponent(Sound.MAIN_BUNDLE)
            : Sound.MAIN_BUNDLE;

        const blob = await response.blob();
        const mp3URL = blob?._data?.name || '';
        // console.log(mp3URL, 'blob', RNFS.DocumentDirectoryPath);

        //directPlyback
        const player = new Sound(mp3URL, mainBundle, error => {
          if (error) {
            console.log('failed to load the sound', error);
            return;
          }
          console.log('loaded successfully using JSON file', player);
        });

        //playing the local audio
        const player2 = new Sound('./Temporary.mp3', mainBundle, error => {
          if (error) {
            console.log('failed to load the sound', error);
            return;
          }
          console.log('Audio playback finished using  local audio', player2);
        });

        //using non-secure URL Sound.MAIN_BUNDLE
        const url =
          'http://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3';
        const player3 = new Sound(url, mainBundle, error => {
          if (error) {
            console.log('failed to load the sound', error);
            return;
          }
          console.log('Audio playback finished using non-secure URL ', player3);
        });

        //using the Secure URL
        const sound2 = new Sound(
          'https://samplesongs.netlify.app/Death%20Bed.mp3',
          mainBundle,
          error => {
            if (error) {
              console.log('failed to load the sound', error);
              return;
            }
            sound.play(() => {
              console.log(
                'Audio playback finished using the Secure URL',
                sound2,
              );
              sound.release();
            });
          },
        );

        //using the FS URL
        const sound = new Sound(
          RNFS.DocumentDirectoryPath + '/audio/' + mp3URL,
          mainBundle,
          error => {
            if (error) {
              console.log('failed to load the sound', error);
              return;
            }
            // if loaded successfully
            console.log('loaded successfully with FS', sound);
          },
        );
        return () => {
          sound.release();
        };
      })
      .catch(ex => {
        console.log('Error', ex);
      });`



and the error is:
`{
"code":"ENSOSSTATUSERRORDOMAIN2003334207",
"domain":"NSOSStatusErrorDomain",
"message":"The operation couldn’t be completed. (OSStatus error 2003334207.)",
"nativeStackIOS":[
"0 0x00000001016f6f80 RCTJSErrorFromCodeMessageAndNSError + 112",
"1 0x00000001016f6ed0 RCTJSErrorFromNSError + 236",
"2 0x00000001015f0534 -[RNSound prepare:withKey:withOptions:withCallback:] + 1288",
"3 CoreFoundation 0x000000018df17c84 3A5F992A-D1CD-312E-BD2E-F7C66343A417 + 203908",
"4 CoreFoundation 0x000000018df17710 3A5F992A-D1CD-312E-BD2E-F7C66343A417 + 202512",
"5 CoreFoundation 0x000000018df17538 3A5F992A-D1CD-312E-BD2E-F7C66343A417 + 202040",
"6 0x000000010169cc8c -[RCTModuleMethod invokeWithBridge:module:arguments:] + 1796",
"7 0x00000001016a0d28 _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicEiN12_GLOBAL__N_117SchedulingContextE + 1688",
"8 0x00000001016a04c4 _ZZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEiENK3$_0clEv + 128",
### "9 0x00000001016a0438 ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 28",
"10 libdispatch.dylib 0x0000000195de113c B7D9D0A6-2414-37F2-9D03-1A25A474E2CF + 8508",
"11 libdispatch.dylib 0x0000000195de2dd4 B7D9D0A6-2414-37F2-9D03-1A25A474E2CF + 15828",
"12 libdispatch.dylib 0x0000000195dea400 B7D9D0A6-2414-37F2-9D03-1A25A474E2CF + 46080",
"13 libdispatch.dylib 0x0000000195deaf30 B7D9D0A6-2414-37F2-9D03-1A25A474E2CF + 48944",
"14 libdispatch.dylib 0x0000000195df5cb4 B7D9D0A6-2414-37F2-9D03-1A25A474E2CF + 93364",
"15 libdispatch.dylib 0x0000000195df5528 B7D9D0A6-2414-37F2-9D03-1A25A474E2CF + 91432",
"16 libsystem_pthread.dylib 0x00000001e9ec8f20 _pthread_wqthread + 288",
"17 libsystem_pthread.dylib 0x00000001e9ec8fc0 start_wqthread + 8"
],
"userInfo":{
}
}`

**Comment by TajGoud** [comment] 2024-05-06 06:08
After removing the mainBundle it worked for me.

> "domain":"NSOSStatusErrorDomain", "message":"The operation couldn’t be completed. (OSStatus error 2003334207.)",
> 
> AnyOne has any idea i have tried with openAI but getting the same errror for everything.
> 
> This is the code: ` fetch('https://api.openai.com/v1/audio/speech', { method: 'POST', body, headers: options.headers, }) .then(async response => { const mainBundle = Platform.OS === 'ios' ? encodeURIComponent(Sound.MAIN_BUNDLE) : Sound.MAIN_BUNDLE;
> 
> ```
>     const blob = await response.blob();
>     const mp3URL = blob?._data?.name || '';
>     // console.log(mp3URL, 'blob', RNFS.DocumentDirectoryPath);
> 
>     //directPlyback
>     const player = new Sound(mp3URL, mainBundle, error => {
>       if (error) {
>         console.log('failed to load the sound', error);
>         return;
>       }
>       console.log('loaded successfully using JSON file', player);
>     });
> 
>     //playing the local audio
>     const player2 = new Sound('./Temporary.mp3', mainBundle, error => {
>       if (error) {
>         console.log('failed to load the sound', error);
>         return;
>       }
>       console.log('Audio playback finished using  local audio', player2);
>     });
> 
>     //using non-secure URL Sound.MAIN_BUNDLE
>     const url =
>       'http://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3';
>     const player3 = new Sound(url, mainBundle, error => {
>       if (error) {
>         console.log('failed to load the sound', error);
>         return;
>       }
>       console.log('Audio playback finished using non-secure URL ', player3);
>     });
> 
>     //using the Secure URL
>     const sound2 = new Sound(
>       'https://samplesongs.netlify.app/Death%20Bed.mp3',
>       mainBundle,
>       error => {
>         if (error) {
>           console.log('failed to load the sound', error);
>           return;
>         }
>         sound.play(() => {
>           console.log(
>             'Audio playback finished using the Secure URL',
>             sound2,
>           );
>           sound.release();
>         });
>       },
>     );
> 
>     //using the FS URL
>     const sound = new Sound(
>       RNFS.DocumentDirectoryPath + '/audio/' + mp3URL,
>       mainBundle,
>       error => {
>         if (error) {
>           console.log('failed to load the sound', error);
>           return;
>         }
>         // if loaded successfully
>         console.log('loaded successfully with FS', sound);
>       },
>     );
>     return () => {
>       sound.release();
>     };
>   })
>   .catch(ex => {
>     console.log('Error', ex);
>   });`
> ```
> 
> and the error is: `{ "code":"ENSOSSTATUSERRORDOMAIN2003334207", "domain":"NSOSStatusErrorDomain", "message":"The operation couldn’t be completed. (OSStatus error 2003334207.)", "nativeStackIOS":[ "0 0x00000001016f6f80 RCTJSErrorFromCodeMessageAndNSError + 112", "1 0x00000001016f6ed0 RCTJSErrorFromNSError + 236", "2 0x00000001015f0534 -[RNSound prepare:withKey:withOptions:withCallback:] + 1288", "3 CoreFoundation 0x000000018df17c84 3A5F992A-D1CD-312E-BD2E-F7C66343A417 + 203908", "4 CoreFoundation 0x000000018df17710 3A5F992A-D1CD-312E-BD2E-F7C66343A417 + 202512", "5 CoreFoundation 0x000000018df17538 3A5F992A-D1CD-312E-BD2E-F7C66343A417 + 202040", "6 0x000000010169cc8c -[RCTModuleMethod invokeWithBridge:module:arguments:] + 1796", "7 0x00000001016a0d28 _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicEiN12_GLOBAL__N_117SchedulingContextE + 1688", "8 0x00000001016a04c4 _ZZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEiENK3$_0clEv + 128",
> 
> ### "9 0x00000001016a0438 ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 28",
> "10 libdispatch.dylib 0x0000000195de113c B7D9D0A6-2414-37F2-9D03-1A25A474E2CF + 8508", "11 libdispatch.dylib 0x0000000195de2dd4 B7D9D0A6-2414-37F2-9D03-1A25A474E2CF + 15828", "12 libdispatch.dylib 0x0000000195dea400 B7D9D0A6-2414-37F2-9D03-1A25A474E2CF + 46080", "13 libdispatch.dylib 0x0000000195deaf30 B7D9D0A6-2414-37F2-9D03-1A25A474E2CF + 48944", "14 libdispatch.dylib 0x0000000195df5cb4 B7D9D0A6-2414-37F2-9D03-1A25A474E2CF + 93364", "15 libdispatch.dylib 0x0000000195df5528 B7D9D0A6-2414-37F2-9D03-1A25A474E2CF + 91432", "16 libsystem_pthread.dylib 0x00000001e9ec8f20 _pthread_wqthread + 288", "17 libsystem_pthread.dylib 0x00000001e9ec8fc0 start_wqthread + 8" ], "userInfo":{ } }`


after removing the mainBundle it worked for me!.

**Comment by albirrkarim** [comment] 2024-05-28 10:26
@TajGoud  how you do that? can you give me some example code?
